# Generated by Django 5.1.6 on 2025-02-11 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedores',
            fields=[
                ('id_proveedor', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre_empresa', models.CharField(max_length=100)),
                ('ruc', models.CharField(max_length=13, unique=True)),
                ('direccion', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'db_table': 'Proveedores',
            },
        ),
        migrations.CreateModel(
            name='Pagos',
            fields=[
                ('id_pago', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('fecha_pago', models.DateField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('referencia', models.CharField(blank=True, max_length=50, null=True)),
                ('metodo_pago', models.CharField(max_length=50)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_pagos.proveedores')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'db_table': 'Pagos',
            },
        ),
        migrations.CreateModel(
            name='Facturas',
            fields=[
                ('id_factura', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_emision', models.DateField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('numero_factura', models.CharField(max_length=20, unique=True)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_pagos.proveedores')),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Facturas',
                'db_table': 'Facturas',
            },
        ),
    ]
